Switch to Guzzle for HTTP calls
pusher/pusher-http-php pull request #289
Opened 2021-03-09 16:24 UTC by elverkilde

## Description

I have put this directly in the constructor instead of a new option. It's a fairly non-standard option IMO, so I think that makes sense.

This will be a breaking change, as support for 7.1 is removed and several deprecated functions have been removed. Will be released with new major version.

Related to #95 and #232.

## CHANGELOG

* [CHANGED] internal HTTP client to Guzzle
* [ADDED] optional client parameter to constructor
* [CHANGED] useTLS is true by default
* [REMOVED] `curl_options` from options
* [REMOVED] customer logger
* [REMOVED] host, port and timeout constructor parameters
* [REMOVED] support for PHP 7.1
* [CHANGED] lower severity level of logging to DEBUG level

2021-03-09 17:27 UTC, GrahamCampbell requested changes

2021-03-09 17:27 UTC, GrahamCampbell commented on composer.json
> +        "guzzlehttp/guzzle": "^7.0",
I'd recommend `^7.2`. In particular, the 7.0.0 release is actually broken. 7.2.0 is the first version to support PHP 8, too.

2021-03-09 17:31 UTC, elverkilde commented on composer.json
>          "php": "^7.1|^8.0",
I notice you put 2 pipes there, is that important?

2021-03-09 17:35 UTC, elverkilde commented on composer.json
>          "php": "^7.1|^8.0",
seems like it's the same, although the double bar and spacing looks better imo. I have updated the dep. Thanks again.

2021-03-10 11:41 UTC, damdo reviewed
Nice one! 👍  A couple of minor comments

2021-03-10 11:41 UTC, damdo commented on src/Pusher.php
>       * @param string            $url_prefix
```suggestion
```

2021-03-10 11:41 UTC, damdo commented on src/Pusher.php
>          $auth_query_string = self::array_implode('=', '&', $params);
We shouldn't need this now that we are returning `$params`.
If that's the case I'd also change the function name.

2021-03-10 11:41 UTC, damdo commented on tests/unit/authQueryStringTest.php
> +        $expected_query_string = [
We could go with:
```suggestion
        $expected_query_params = [
```
and also change the function name.

2021-03-11 13:16 UTC, GrahamCampbell requested changes

2021-03-11 13:16 UTC, GrahamCampbell commented on tests/unit/socketAuthTest.php
> +class socketAuthTest extends PHPUnit\Framework\TestCase
PSR-1+4 says class names must start with an uppercase letter, and the filename must match the classname.

2021-03-16 17:21 UTC, damdo approved these changes

2021-03-17 08:59 UTC, merged

2024-01-24 21:22 UTC, caendesilva commented
@elverkilde Hey! Sorry for pinging you here but I just wanted to check something. Was the removal of `curl_options` an intended change, or just a side effect?

The reason I'm asking is because it breaks self signed certificates (which are very useful for local development) when using Laravel Broadcasting.

Since `v5.0.3` no longer works on Laravel 10, this means that there is now no way to use self signed certificates when self-hosting Pusher, for example with Soketi (who documents this issue here https://docs.soketi.app/getting-started/backend-configuration/laravel-broadcasting#self-signed-certificates)

If this was an intentional removal, would you mind letting us know why it was removed? Else, would it be possible to get it added back to the package? I'm happy to try making a PR.